In [25]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv('Amazon_Unlocked_Mobile.csv')

In [27]:
df.head()

Product Name Brand Name   Price  \
0  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
1  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
2  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
3  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
4  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   

   Rating                                            Reviews  Review Votes  
0       5  I feel so LUCKY to have found this used (phone...           1.0  
1       4  nice phone, nice up grade from my pantach revu...           0.0  
2       5                                       Very pleased           0.0  
3       4  It works good but it goes slow sometimes but i...           0.0  
4       4  Great phone to replace my lost phone. The only...           0.0

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Reviews'],
                                                   df['Rating'], 
                                                    random_state=0)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413840 entries, 0 to 413839
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   Product Name  413840 non-null  object 
 1   Brand Name    348669 non-null  object 
 2   Price         407907 non-null  float64
 3   Rating        413840 non-null  int64  
 4   Reviews       413770 non-null  object 
 5   Review Votes  401544 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 18.9+ MB


In [7]:
print( X_train.iloc[14]) 

who can i talk to about getting a replacement because when i received this phone the charger port was stretched out which made it hard for me to keep my phone charged. but all together the phone is great , i just need to know who to contact about sending me an replacement. thanks


In [29]:
df.dropna(inplace=True)

# Remove any 'neutral' ratings equal to 3
df = df[df['Rating'] != 3]

# Encode 4s and 5s as 1 (rated positively)
# Encode 1s and 2s as 0 (rated poorly)
df['Positively Rated'] = np.where(df['Rating'] > 3, 1, 0)

In [30]:
from sklearn.model_selection import train_test_split

# Split data into train and test subsets
X_train, X_test, y_train, y_test = train_test_split(df['Reviews'], 
                                                    df['Positively Rated'], 
                                                    random_state=0)

In [31]:
X_train.shape

(231202,)

In [32]:
X_test.shape

(77068,)

In [33]:
print( X_train.iloc[11]) 

not bad but poor battery life and shutdown often to factory settings


In [34]:
from sklearn.feature_extraction.text import CountVectorizer

docs = np.array([
    'It is good',
    'It works good but it goes slow sometimes but its a very good phone I love it',
    'Phone works great. No problems at all',])

# Fit the CountVectorizer to the training data 
vect1=CountVectorizer().fit(docs)

# transform the documents in the training data to a document-term matrix. 
bag = vect1.transform(docs)

In [35]:
vect1.vocabulary_

{'it': 7,
 'is': 6,
 'good': 4,
 'works': 16,
 'but': 2,
 'goes': 3,
 'slow': 13,
 'sometimes': 14,
 'its': 8,
 'very': 15,
 'phone': 11,
 'love': 9,
 'great': 5,
 'no': 10,
 'problems': 12,
 'at': 1,
 'all': 0}

In [36]:
vect1.get_feature_names_out()

array(['all', 'at', 'but', 'goes', 'good', 'great', 'is', 'it', 'its',
       'love', 'no', 'phone', 'problems', 'slow', 'sometimes', 'very',
       'works'], dtype=object)

In [37]:
X_train.shape

(231202,)

In [38]:
X_test.shape

(77068,)

In [39]:
from sklearn.feature_extraction.text import CountVectorizer

docs = np.array([
    'It is good',
    'It works good but it goes slow sometimes but its a very good phone I love it',
    'Phone works great. No problems at all',])

# Fit the CountVectorizer to the training data 
vect1=CountVectorizer().fit(docs)

# transform the documents in the training data to a document-term matrix. 
bag = vect1.transform(docs)

In [40]:
vect1.vocabulary_

{'it': 7,
 'is': 6,
 'good': 4,
 'works': 16,
 'but': 2,
 'goes': 3,
 'slow': 13,
 'sometimes': 14,
 'its': 8,
 'very': 15,
 'phone': 11,
 'love': 9,
 'great': 5,
 'no': 10,
 'problems': 12,
 'at': 1,
 'all': 0}

In [41]:
vect1.get_feature_names_out()

array(['all', 'at', 'but', 'goes', 'good', 'great', 'is', 'it', 'its',
       'love', 'no', 'phone', 'problems', 'slow', 'sometimes', 'very',
       'works'], dtype=object)

In [42]:
# Fit the CountVectorizer to the training data 
review1 = CountVectorizer().fit(X_train)

# transform the documents in the training data to a document-term matrix. 
X_train_vectorized1 = review1.transform(X_train) #bag of words (unique token in vectors format)


print(len(review1.get_feature_names_out()))
X_train_vectorized1.shape

53270


(231202, 53270)

In [43]:
review1.vocabulary_

{'excellent': 18395,
 'exactly': 18305,
 'as': 5884,
 'described': 14618,
 'thanks': 46856,
 'love': 28632,
 'this': 47186,
 'phone': 35057,
 'bought': 8483,
 'about': 3299,
 'months': 30738,
 'ago': 4276,
 'and': 4996,
 'now': 32431,
 'can': 9636,
 'give': 21613,
 'genuine': 21427,
 'review': 40259,
 'that': 46907,
 'being': 7516,
 'said': 41011,
 'model': 30565,
 'is': 26009,
 'probably': 36772,
 'already': 4658,
 'obsolete': 32682,
 'very': 50473,
 'similar': 42867,
 'to': 47634,
 'my': 31264,
 'son': 43921,
 'lg': 27813,
 'g3': 21023,
 'which': 51649,
 'set': 42211,
 'him': 23528,
 'back': 6774,
 '600': 2306,
 'nuf': 32505,
 'great': 22232,
 'camera': 9521,
 'superior': 45577,
 'quality': 37797,
 'battery': 7179,
 'life': 27902,
 'amazing': 4784,
 'front': 20711,
 'flash': 19949,
 'dual': 16378,
 'sim': 42833,
 'fm': 20153,
 'radio': 38093,
 'storage': 44967,
 'speed': 44272,
 'sleek': 43216,
 'problem': 36803,
 'free': 20540,
 'reliable': 39393,
 'fun': 20850,
 'just': 26747,
 'bu

In [44]:
from sklearn.linear_model import LogisticRegression

# Train the model
model = LogisticRegression()
model.fit(X_train_vectorized1, y_train)

#x_train
#vectors (unique tokens)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [45]:
from sklearn.metrics import roc_auc_score

# Predict the transformed test documents
predictions = model.predict(review1.transform(X_test))
y_proba = model.predict_proba(review1.transform(X_test))
                              
print('AUC: ', roc_auc_score(y_test, y_proba[:,1]))   

AUC:  0.9756714112826295


In [46]:
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier()

In [47]:
from sklearn.linear_model import LogisticRegression

# Train the model
knn = LogisticRegression()
knn.fit(X_train_vectorized1, y_train)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [48]:
model.coef_

array([[-0.70598052,  0.2402608 ,  0.03600628, ...,  0.00096758,
         0.12479667,  0.01020885]])

In [49]:
model.coef_[0].argsort()

array([52328, 26722, 21241, ..., 18533, 18358, 18359], dtype=int64)

In [50]:
# get the feature names as numpy array
feature_names = np.array(review1.get_feature_names_out())

# Sort the coefficients from the model
sorted_coef_index = model.coef_[0].argsort()

# Find the 10 smallest and 10 largest coefficients
print('Smallest Coefs:' )
print(feature_names[sorted_coef_index[:10]])
      
print('\n Largest Coefs:')      
print(feature_names[sorted_coef_index[:-11:-1]])

Smallest Coefs:
['worst' 'junk' 'garbage' 'unusable' 'useless' 'waste' 'false' 'terrible'
 'horrible' 'scam']

 Largest Coefs:
['excelente' 'excelent' 'exelente' 'loves' 'loving' 'excellent' 'perfecto'
 'complaints' 'love' 'bien']


In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer


docs = np.array([
    'It is good',
    'It works good but it goes slow sometimes but its a very good phone I love it',
    'Phone works great. No problems at all',])

vect2 = TfidfVectorizer().fit(docs)
bag2 = vect2.transform(docs)

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Fit the TfidfVectorizer to the training data 
review2 = TfidfVectorizer(min_df=5).fit(X_train) #raw unique tokens

In [59]:
len(review2.get_feature_names_out())

18023

In [54]:
X_train_vectorized2 = review2.transform(X_train) #unique tokens in vector format

model = LogisticRegression()
model.fit(X_train_vectorized2, y_train)

predictions = model.predict(review2.transform(X_test))
y_proba = model.predict_proba(review2.transform(X_test))
                              
print('AUC: ', roc_auc_score(y_test, y_proba[:,1])) 

C:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


AUC:  0.9821743288701912


In [56]:
model.predict(review2.transform(['phone is good','an issue, phone is not working']))

array([1, 0])

In [60]:
docs = np.array([
    'It is good',
    'It works good but it goes slow sometimes but its a very good phone I love it',
    'Phone works great. No problems at all',])

vect3=CountVectorizer(ngram_range=(1,2)).fit(docs)
bag3=vect3.transform(docs)

In [61]:
vect3.vocabulary_

{'it': 15,
 'is': 13,
 'good': 8,
 'it is': 17,
 'is good': 14,
 'works': 36,
 'but': 3,
 'goes': 6,
 'slow': 30,
 'sometimes': 32,
 'its': 19,
 'very': 34,
 'phone': 25,
 'love': 21,
 'it works': 18,
 'works good': 37,
 'good but': 9,
 'but it': 4,
 'it goes': 16,
 'goes slow': 7,
 'slow sometimes': 31,
 'sometimes but': 33,
 'but its': 5,
 'its very': 20,
 'very good': 35,
 'good phone': 10,
 'phone love': 26,
 'love it': 22,
 'great': 11,
 'no': 23,
 'problems': 28,
 'at': 1,
 'all': 0,
 'phone works': 27,
 'works great': 38,
 'great no': 12,
 'no problems': 24,
 'problems at': 29,
 'at all': 2}

In [62]:
review3 = CountVectorizer(min_df=5, ngram_range=(1,2)).fit(X_train) #raw unique tokens

X_train_vectorized3 = review3.transform(X_train) #vectorized unique tokens

In [63]:
len(review3.get_feature_names_out())

200173

In [64]:
model = LogisticRegression()
model.fit(X_train_vectorized3, y_train)

predictions = model.predict(review3.transform(X_test))
y_proba = model.predict_proba(review3.transform(X_test))
                              
print('AUC: ', roc_auc_score(y_test, y_proba[:,1])) 

C:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


AUC:  0.9894970093050988


In [65]:
feature_names = np.array(review3.get_feature_names_out())

sorted_coef_index = model.coef_[0].argsort()

print('Smallest Coefs:' )
print(feature_names[sorted_coef_index[:10]])
      
print('\n Largest Coefs:')      
print(feature_names[sorted_coef_index[:-11:-1]])

Smallest Coefs:
['worst' 'no good' 'not worth' 'junk' 'not good' 'not satisfied'
 'not happy' 'garbage' 'terrible' 'horrible']

 Largest Coefs:
['excelent' 'excelente' 'excellent' 'not bad' 'exelente' 'perfect'
 'awesome' 'no problems' 'no issues' 'amazing']


In [66]:
print(model.predict(review3.transform(['phone is okay',
                                    'the phone is not smooth'])))

[1 0]
